# Generated by Django 2.2.6 on 2019-10-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20191022_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=True, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='Is superuser?'),
        ),
    ]
