# Generated by Django 2.2.6 on 2019-10-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20191023_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
