# Generated by Django 2.2.6 on 2019-10-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20191023_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earnings',
            options={'ordering': ('-earning_date',)},
        ),
        migrations.AlterModelOptions(
            name='payments',
            options={'ordering': ('-payment_date',)},
        ),
        migrations.RenameField(
            model_name='earnings',
            old_name='date',
            new_name='earning_date',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='date',
            new_name='payment_date',
        ),
    ]
