# Generated by Django 2.2.6 on 2019-10-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='full name')),
                ('email', models.EmailField(max_length=255, verbose_name='email address')),
                ('phone_number', models.CharField(max_length=60, verbose_name='phone number')),
                ('skype', models.CharField(blank=True, max_length=255, null=True, verbose_name='skype')),
                ('website', models.CharField(blank=True, max_length=255, null=True, verbose_name='website')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
    ]
