# Generated by Django 2.2.6 on 2019-10-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20191025_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmanager',
            name='avatar',
            field=models.CharField(choices=[('m-01', 'Male-01'), ('f-01', 'Female-01'), ('m-02', 'Male-02'), ('f-02', 'Female-02'), ('m-03', 'Male-03'), ('f-03', 'Female-03'), ('m-04', 'Male-04'), ('f-04', 'Female-04'), ('m-05', 'Male-05'), ('f-05', 'Female-05'), ('m-06', 'Male-06'), ('f-06', 'Female-06'), ('m-07', 'Male-07'), ('f-07', 'Female-07'), ('m-08', 'Male-08'), ('f-08', 'Female-08'), ('m-09', 'Male-09'), ('f-09', 'Female-09'), ('m-10', 'Male-10'), ('f-10', 'Female-10')], default='m-01', max_length=32, null=True, verbose_name='avatar'),
        ),
    ]
