# Generated by Django 2.2.6 on 2019-10-23 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191023_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earnings',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
